import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Hero } from '@/components/home/Hero';
import { Description } from '@/components/home/Description';
import { Header } from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';
import '@/sass/globals.sass';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Future World',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <Hero />
        <Description />
        {children}
        <Footer />
      </body>
    </html>
  );
}
